apps/L1AB/Instagram/instagram-backend/specs/resolvers/mutations/followers/create-followers.spec.ts
apps/L1AB/Instagram/instagram-backend/specs/resolvers/mutations/index.spec.ts
apps/L1AB/Instagram/instagram-backend/specs/resolvers/queries/post/get-posts-by-followers-id.spec.ts
apps/L1AB/Instagram/instagram-backend/specs/resolvers/queries/story/get-all-stories.spec.ts
apps/L1AB/Instagram/instagram-backend/src/models/story-model.ts
apps/L1AB/Instagram/instagram-backend/src/resolvers/mutations/followers/create-followers.ts
apps/L1AB/Instagram/instagram-backend/src/resolvers/mutations/save/create-save.ts
apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/post/get-posts-by-followers-id.ts
apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/post/index.ts
apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/story/get-all-stories.ts
apps/L1AB/Instagram/instagram-backend/src/schemas/followers.schema.ts
apps/L1AB/Instagram/instagram-backend/src/schemas/posts.schema.ts
apps/L1AB/Instagram/instagram-backend/src/schemas/story.schema.ts

getStories and GetPostsByFollowers

2545 dagasan humuusiinhee postiig avah be

---

apps/L1AB/Instagram/instagram-frontend/specs/components/NewsFeed.spec.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/NewsFeed.tsx
apps/L1AB/Instagram/instagram-frontend/src/graphql/followers.graphql
apps/L1AB/Instagram/instagram-frontend/src/graphql/post.graphql

zuvhun dagadag humuusiinhe post-g harna

feat(ig-be): zuvhun dagadag humuusiinhe post-g harna

---

apps/L1AB/Instagram/instagram-backend/specs/resolvers/queries/saved/get-all-saved-post.spec.ts
apps/L1AB/Instagram/instagram-backend/specs/resolvers/queries/saved/get-saved-by-postid.spec.ts
apps/L1AB/Instagram/instagram-backend/src/models/saved-model.ts
apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/save/get-all-saved-post.ts
apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/save/get-saved-by-postid.ts
apps/L1AB/Instagram/instagram-backend/src/schemas/saved.schema.ts
apps/L1AB/Instagram/instagram-frontend/specs/components/PostCardLikeSection.spec.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/PostCardLikeSection.tsx
apps/L1AB/Instagram/instagram-frontend/src/graphql/saved.graphql

feat(ig-be): savedpost query

---

apps/L1AB/hotel-booking/frontend/specs/components/main/CheckingQpay.spec.tsx
apps/L1AB/hotel-booking/frontend/specs/components/main/Footer.spec.tsx
apps/L1AB/hotel-booking/frontend/specs/components/main/Header.spec.tsx
apps/L1AB/hotel-booking/frontend/specs/components/main/assets/CheckingConfirm.spec.tsx
apps/L1AB/hotel-booking/frontend/src/app/(main)/(checkout)/checkconfirm/page.tsx
apps/L1AB/hotel-booking/frontend/src/app/(main)/(checkout)/checkingqpay/page.tsx
apps/L1AB/hotel-booking/frontend/src/app/(main)/(checkout)/checkouthome/page.tsx
apps/L1AB/hotel-booking/frontend/src/app/(main)/bookings/[booking]/page.tsx
apps/L1AB/hotel-booking/frontend/src/app/(main)/layout.tsx
apps/L1AB/hotel-booking/frontend/src/components/main/CheckingConfirm.tsx
apps/L1AB/hotel-booking/frontend/src/components/main/CheckingQpay.tsx
apps/L1AB/hotel-booking/frontend/src/components/main/CheckoutHome.tsx
apps/L1AB/hotel-booking/frontend/src/components/main/Footer.tsx
apps/L1AB/hotel-booking/frontend/src/components/main/Header.tsx
apps/L1AB/hotel-booking/frontend/src/components/main/index.ts

Main-Layout- Booking Header,Foorter  zursan. Main-checkConfirm, CheckOutHome, CheckingQpay folder uusgesen

feat: main-Layout, main-3folder

---

apps/L1AB/Instagram/instagram-backend/specs/resolvers/mutations/likes/create-like.spec.ts
apps/L1AB/Instagram/instagram-backend/specs/resolvers/queries/notifications/get-notifications-by-user-id.spec.ts
apps/L1AB/Instagram/instagram-backend/src/models/notifications-model.ts
apps/L1AB/Instagram/instagram-backend/src/resolvers/mutations/likes/create-like.ts
apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/index.ts
apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/notificiations/get-notifications-by-user-id.ts
apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/notificiations/index.ts
apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/save/get-saved-by-postid.ts
apps/L1AB/Instagram/instagram-backend/src/schemas/notifications.schema.ts

like hiihed notifications uusdeg query

feat(ig-[be]): like notifications

---

apps/L1AB/Instagram/instagram-backend/specs/resolvers/queries/notifications/get-notifications-by-user-id.spec.ts
apps/L1AB/Instagram/instagram-backend/src/models/notifications-model.ts
apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/notificiations/get-notifications-by-user-id.ts
apps/L1AB/Instagram/instagram-backend/src/schemas/notifications.schema.ts

feat(ig-be): get notify

---

apps/L1AB/Instagram/instagram-frontend/specs/components/PostCardLikeSection.spec.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/PostCardLikeSection.tsx
apps/L1AB/Instagram/instagram-frontend/src/graphql/saved.graphql

feat([fe]-ig): saveButton

---

apps/L1AB/hotel-booking/frontend/specs/components/main/BookingDetailRoom.spec.tsx
apps/L1AB/hotel-booking/frontend/specs/components/main/BoookingDetailBooked.spec.tsx
apps/L1AB/hotel-booking/frontend/src/app/(main)/bookings/[booking]/page.tsx
apps/L1AB/hotel-booking/frontend/src/components/main/BookingDetailBooked.tsx
apps/L1AB/hotel-booking/frontend/src/components/main/BookingDetailRoom.tsx
apps/L1AB/hotel-booking/frontend/src/components/main/BookingDetails.tsx
apps/L1AB/hotel-booking/frontend/src/components/main/index.ts

feat: booooking Details 2 salgav

---

apps/L1AB/hotel-booking/frontend/specs/components/main/CheckingBookingLeft.spec.tsx
apps/L1AB/hotel-booking/frontend/specs/components/main/CheckingBookingRight.spec.tsx
apps/L1AB/hotel-booking/frontend/src/components/main/CheckingBookingLeft.tsx
apps/L1AB/hotel-booking/frontend/src/components/main/CheckingBookingRight.tsx
apps/L1AB/hotel-booking/frontend/src/components/main/index.ts

Check OutHome 2 salgav qpay hooson

feat: check Out Home salgav

---

apps/L1AB/hotel-booking/frontend/specs/components/main/FilterHotels.spec.tsx
apps/L1AB/hotel-booking/frontend/src/components/main/FilterHotels.tsx
apps/L1AB/hotel-booking/frontend/src/graphql/hotelamenities.graphql

search, ratings and star filters

feat(hotel booking frontend): filter-hotels

---

apps/L1AB/Instagram/instagram-backend/src/models/user-model.ts
apps/L1AB/Instagram/instagram-frontend/specs/components/PostCard.spec.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/LeftSideBar.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/PostCard.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/PostDetail.tsx

feat(ig-fe): zasav

---

apps/L1AB/Instagram/instagram-backend/specs/resolvers/queries/user/get-suggeted-users-query.spec.ts
apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/user/get-suggested-users-query.ts
apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/user/index.ts
apps/L1AB/Instagram/instagram-backend/src/schemas/user-schema.ts

get suggested users query hiiv.

feat(ig-be): get suggested users

---

apps/L1AB/Instagram/instagram-frontend/specs/components/SuggestCard.spec.tsx
apps/L1AB/Instagram/instagram-frontend/specs/components/UsersMap.spec.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/PostCard.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/SuggestCard.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/UsersMap.tsx
apps/L1AB/Instagram/instagram-frontend/src/graphql/all.graphql

feat(ig-fe): suggested users hiiv

---

apps/L1E/tinder/tinder-fe/specs/components/Date.spec.tsx
apps/L1E/tinder/tinder-fe/specs/components/LeftSideBar.spec.tsx
apps/L1E/tinder/tinder-fe/specs/components/ProfilePage.spec.tsx
apps/L1E/tinder/tinder-fe/src/app/libgun/page.tsx
apps/L1E/tinder/tinder-fe/src/components/profile/Date.tsx
apps/L1E/tinder/tinder-fe/src/components/profile/ImagesSection.tsx
apps/L1E/tinder/tinder-fe/src/components/profile/LeftSideBar.tsx
apps/L1E/tinder/tinder-fe/src/components/profile/MainSection.tsx
apps/L1E/tinder/tinder-fe/src/components/profile/Profile.tsx
apps/L1E/tinder/tinder-fe/src/components/profile/ProfileInputForm.tsx

feat(tinder): add profile page

---

apps/L1AB/Instagram/instagram-backend/specs/resolvers/mutations/post/create-post.spec.ts
apps/L1AB/Instagram/instagram-backend/src/resolvers/mutations/post/create-post.ts
apps/L1AB/Instagram/instagram-backend/src/schemas/posts.schema.ts

feat(ig-be): createpost mutation zasav

---

apps/L1E/hrms/hrms-fe/specs/components/Leave.spec.tsx
apps/L1E/hrms/hrms-fe/specs/components/LeaveCalendar.spec.tsx
apps/L1E/hrms/hrms-fe/specs/components/MyRequest.spec.tsx
apps/L1E/hrms/hrms-fe/specs/components/PaidLeave.spec.tsx
apps/L1E/hrms/hrms-fe/specs/components/RemoteWork.spec.tsx
apps/L1E/hrms/hrms-fe/specs/components/RequestSchema.spec.tsx
apps/L1E/hrms/hrms-fe/specs/components/RequestStory.spec.tsx
apps/L1E/hrms/hrms-fe/src/components/Leave.tsx
apps/L1E/hrms/hrms-fe/src/components/LeaveCalendar.tsx
apps/L1E/hrms/hrms-fe/src/components/MyRequest.tsx
apps/L1E/hrms/hrms-fe/src/components/PaidLeave.tsx
apps/L1E/hrms/hrms-fe/src/components/RemoteWork.tsx
apps/L1E/hrms/hrms-fe/src/components/RequestStory.tsx

feat(hrms): fe-myrequest

---

apps/L1AB/Instagram/instagram-frontend/src/graphql/mutation.graphql

feat(ig-fe): graphql zasav

---

apps/L1AB/hotel-booking/backend/specs/resolvers/mutations/user/sign-in.spec.ts
apps/L1AB/hotel-booking/backend/specs/resolvers/queries/amenity/get-amenities.spec.ts
apps/L1AB/hotel-booking/backend/specs/resolvers/queries/user/get-me.spec.ts
apps/L1AB/hotel-booking/backend/src/handler.ts
apps/L1AB/hotel-booking/backend/src/resolvers/mutations/user/sign-in.ts
apps/L1AB/hotel-booking/backend/src/resolvers/queries/user/get-me.ts
apps/L1AB/hotel-booking/backend/src/resolvers/queries/user/index.ts
apps/L1AB/hotel-booking/backend/src/schemas/user.schema.ts
apps/L1AB/hotel-booking/backend/src/types/index.d.ts

feat: bE get-me-query

---

apps/L1AB/Instagram/instagram-backend/src/resolvers/mutations/post/create-post.ts
apps/L1AB/Instagram/instagram-frontend/specs/components/NewsFeed.spec.tsx
apps/L1AB/Instagram/instagram-frontend/specs/components/PostCard.spec.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/CreatePost.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/CreatePostDescription.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/NewsFeed.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/PostCard.tsx
apps/L1AB/Instagram/instagram-frontend/src/graphql/post.graphql

feat(ig-fe): ooriin post-g harah

---

apps/L1AB/Instagram/instagram-frontend/src/components/LogoutButton.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/PostCardLikeSection.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/ProfilePostsSection.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/SuggestCard.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/UsersMap.tsx

feat(ig-[fe]): jjig fixes

---

apps/L1AB/hotel-booking/frontend/src/components/providers/Auth.Provider.tsx

email: admin@gmail.com
password: admin12345678

feat(hotel-booking-frontend): push to admin/hotels

---

apps/L1AB/hotel-booking/frontend/specs/components/main/Header.spec.tsx
apps/L1AB/hotel-booking/frontend/specs/components/main/UserSettings.spec.tsx
apps/L1AB/hotel-booking/frontend/src/components/main/Header.tsx
apps/L1AB/hotel-booking/frontend/src/components/main/UserContainer.tsx
apps/L1AB/hotel-booking/frontend/src/components/main/UserSettings.tsx

main header user info useriin email avdag bolson

feat: fe signed user info header

---

apps/L1AB/Instagram/instagram-backend/specs/resolvers/queries/story/get-all-stories.spec.ts
apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/story/get-all-stories.ts

feat(ig-be): getallstories query

---

apps/L1AB/Instagram/instagram-frontend/src/app/(main)/home/page.tsx
apps/L1AB/Instagram/instagram-frontend/src/app/(main)/profile/page.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/LogoutButton.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/MoreButton.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/NewsFeed.tsx

feat(ig-fe): jijig fixes

---

apps/L1AB/Instagram/instagram-backend/specs/resolvers/queries/post/get-posts-by-followers-id.spec.ts
apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/post/get-posts-by-followers-id.ts

feat(ig-[be]): getposts query

---

apps/L1AB/Instagram/instagram-backend/specs/resolvers/queries/post/get-posts-by-followers-id.spec.ts
apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/post/get-posts-by-followers-id.ts
apps/L1AB/Instagram/instagram-frontend/specs/components/NewsFeed.spec.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/CreatePost.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/HomeButton.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/NewsFeed.tsx

feat(ig-fe): getpostson fe

---

apps/L1AB/Instagram/instagram-frontend/specs/components/CreatePostUpload.spec.tsx
apps/L1AB/Instagram/instagram-frontend/specs/components/NewsFeed.spec.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/CreatePost.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/CreatePostUpload.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/CreateStory.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/NewsFeed.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/PostCard.tsx

feat(ig-fe): createpost and story loading

---

apps/L1E/hrms/hrms-be/src/models/request.model.ts
apps/L1E/hrms/hrms-be/src/resolvers/mutations/requests/create-request.ts
apps/L1E/hrms/hrms-be/src/schemas/requests.schema.ts

feat(hrms): [be]-fix

---

apps/L1AB/Instagram/instagram-frontend/src/components/CreateButton.tsx
apps/L1AB/Instagram/instagram-frontend/src/components/CreateStory.tsx

feat(ig-fe): createstory

---

apps/L1AB/hotel-booking/frontend/specs/components/main/FilterHotels1.spec.tsx
apps/L1AB/hotel-booking/frontend/specs/components/main/assets/FilterHotelCard.spec.tsx
apps/L1AB/hotel-booking/frontend/src/components/main/FilterHotels.tsx
apps/L1AB/hotel-booking/frontend/src/components/main/assets/FilterHotelCard.tsx
apps/L1AB/hotel-booking/frontend/src/components/main/assets/HotelSorting.tsx

Recommended sort has been done

feat(hotel-booking): recommended sort

---

apps/L1AB/Instagram/instagram-backend/specs/resolvers/queries/post/get-post-by-user-id.spec.ts
apps/L1AB/Instagram/instagram-backend/src/resolvers/queries/post/get-post-by-user-id.ts

feat(ig-be): getpostbyuserid

---

apps/L1AB/hotel-booking/backend/src/models/room-model.ts
apps/L1AB/hotel-booking/backend/src/schemas/room.schema.ts

perf(hotel-booking-backend): backend

---

apps/L1AB/Instagram/instagram-frontend/src/components/MyPostDetail.tsx

feat(ig-ge): ga

---

apps/L1E/hrms/hrms-be/src/schemas/employee.schema.ts
apps/L1E/hrms/hrms-be/src/schemas/requests.schema.ts

feat(hrms): be-fix

---

apps/L1FG/concert-ticket/backend/project.json
apps/L1FG/concert-ticket/backend/specs/resolvers/mutations/create-test.spec.ts
apps/L1FG/concert-ticket/backend/specs/resolvers/mutations/index.spec.ts
apps/L1FG/concert-ticket/backend/specs/resolvers/mutations/sample-mutation.spec.ts
apps/L1FG/concert-ticket/backend/specs/resolvers/queries/index.spec.ts
apps/L1FG/concert-ticket/backend/src/models/test.model.ts
apps/L1FG/concert-ticket/backend/src/resolvers/mutations/create-test.ts
apps/L1FG/concert-ticket/backend/src/resolvers/mutations/index.ts
apps/L1FG/concert-ticket/backend/src/schemas/index.ts
apps/L1FG/concert-ticket/backend/src/schemas/test.schema.ts

feat(backend): push testing

---

apps/L1FG/real-state/backend/jest.config.ts
apps/L1FG/real-state/backend/specs/resolvers/mutations/index.spec.ts
apps/L1FG/real-state/backend/specs/resolvers/mutations/user/change-password.spec.ts
apps/L1FG/real-state/backend/specs/resolvers/mutations/user/login.spec.ts
apps/L1FG/real-state/backend/specs/resolvers/mutations/user/register.spec.ts
apps/L1FG/real-state/backend/specs/resolvers/mutations/user/request-change-password.spec.ts
apps/L1FG/real-state/backend/src/library/nodemailer.ts
apps/L1FG/real-state/backend/src/models/index.ts
apps/L1FG/real-state/backend/src/models/user.model.ts
apps/L1FG/real-state/backend/src/resolvers/mutations/index.ts
apps/L1FG/real-state/backend/src/resolvers/mutations/user/change-password.ts
apps/L1FG/real-state/backend/src/resolvers/mutations/user/index.ts
apps/L1FG/real-state/backend/src/resolvers/mutations/user/login.ts
apps/L1FG/real-state/backend/src/resolvers/mutations/user/register.ts
apps/L1FG/real-state/backend/src/resolvers/mutations/user/request-change-password.ts
apps/L1FG/real-state/backend/src/schemas/index.ts
apps/L1FG/real-state/backend/src/schemas/user.schema.ts

feat(real-estate-backend user): not yet token

---

apps/L1FG/instagram/backend/specs/resolvers/mutations/comment/create-comment-like.spec.ts
apps/L1FG/instagram/backend/src/resolvers/comment/comment-detail-type/comment-liked.ts
apps/L1FG/instagram/backend/src/resolvers/mutations/comment/create-comment-like.ts
apps/L1FG/instagram/backend/src/schemas/comment.schema.ts
apps/L1FG/instagram/frontend/src/components/profile/Profile.tsx

commentLike backend count nemdeg bolson

feat: commentLike backend count nemeh

---

apps/L1FG/concert-ticket/frontend/src/components/login/SignIn.tsx

login hesegt otp bolon newtreh hesegt

fix: login heseg newterwel otp usreh heseg uurchlult hiiw

---

apps/L1FG/instagram/frontend/src/components/home-post/Avatar.tsx
apps/L1FG/instagram/frontend/src/components/home-post/ProfileHover.tsx
apps/L1FG/instagram/frontend/src/components/profile/Profile.tsx
apps/L1FG/instagram/frontend/src/components/profile/comment/CommentLike.tsx
apps/L1FG/instagram/frontend/src/components/profile/profilePost/PostModal.tsx
apps/L1FG/instagram/frontend/src/features/profile/comment/Comment.tsx
apps/L1FG/instagram/frontend/src/features/profile/comment/CreateComment.tsx
apps/L1FG/instagram/frontend/src/features/profile/comment/GetComments.tsx

feat: profileHover frontend fix

---

apps/L1FG/instagram/backend/specs/resolvers/mutations/comment/create-comment-like.spec.ts
apps/L1FG/instagram/backend/specs/resolvers/mutations/comment/delete-comment-like.spec.ts
apps/L1FG/instagram/backend/specs/resolvers/queries/comment/get-comments.spec.ts
apps/L1FG/instagram/backend/specs/resolvers/utils/comment-like/create-commentlike-and-update-comment.spec.ts
apps/L1FG/instagram/backend/specs/resolvers/utils/comment-like/make-comment-like-notification.spec.ts
apps/L1FG/instagram/backend/specs/resolvers/utils/comment-like/validate-comment-like-when-deleting.spec.ts
apps/L1FG/instagram/backend/specs/resolvers/utils/comment-like/validate-commentlike-comment-owneruser.spec.ts
apps/L1FG/instagram/backend/src/resolvers/mutations/comment/create-comment-like-utils/create-commentlike-and-update-comment.ts
apps/L1FG/instagram/backend/src/resolvers/mutations/comment/create-comment-like-utils/make-comment-like-notification.ts
apps/L1FG/instagram/backend/src/resolvers/mutations/comment/create-comment-like-utils/validate-commentlike-comment-owneruser.ts
apps/L1FG/instagram/backend/src/resolvers/mutations/comment/create-comment-like.ts
apps/L1FG/instagram/backend/src/resolvers/mutations/comment/delete-comment-like-utils/validate-comment-like-when-deleting.ts
apps/L1FG/instagram/backend/src/resolvers/mutations/comment/delete-comment-like.ts
apps/L1FG/instagram/backend/src/resolvers/mutations/comment/index.ts
apps/L1FG/instagram/backend/src/resolvers/queries/comment/get-comments.ts
apps/L1FG/instagram/backend/src/schemas/comment-like.schema.ts
apps/L1FG/instagram/backend/src/schemas/comment.schema.ts
apps/L1FG/instagram/backend/src/schemas/post-like.schema.ts

comment like plus minus

---

apps/L1FG/real-state/frontend/cypress/e2e/my-estate-id/page.cy.tsx
apps/L1FG/real-state/frontend/specs/components/addEstate/DescriptionSection.spec.tsx
apps/L1FG/real-state/frontend/specs/components/addEstate/TownDetails.spec.tsx
apps/L1FG/real-state/frontend/specs/components/utils/use-form-state.spec.tsx
apps/L1FG/real-state/frontend/src/app/add-estate/page.tsx
apps/L1FG/real-state/frontend/src/app/my-estates/[id]/page.tsx
apps/L1FG/real-state/frontend/src/components/addEstate/DescriptionSection.tsx
apps/L1FG/real-state/frontend/src/components/addEstate/TownDetails.tsx
apps/L1FG/real-state/frontend/src/components/utils/use-form-state.ts

[frontend] Successfully added 2 components for editing page

---

apps/L1FG/real-state/frontend/specs/components/utils/use-form-state.spec.tsx
apps/L1FG/real-state/frontend/src/app/my-estates/[id]/page.tsx
apps/L1FG/real-state/frontend/src/components/utils/use-form-state.ts

Completion date, windows and bathroom

[frontend] Added 2 more components to edit page

---

apps/L1FG/real-state/frontend/cypress/e2e/my-estate-id/page.cy.tsx
apps/L1FG/real-state/frontend/specs/components/addEstate/FloorDetailsSection.spec.tsx
apps/L1FG/real-state/frontend/specs/components/addEstate/ImagesSection.spec.tsx
apps/L1FG/real-state/frontend/specs/components/addEstate/WindowsSection.spec.tsx
apps/L1FG/real-state/frontend/src/app/add-estate/page.tsx
apps/L1FG/real-state/frontend/src/app/my-estates/[id]/page.tsx
apps/L1FG/real-state/frontend/src/components/addEstate/ImagesSection.tsx
apps/L1FG/real-state/frontend/src/components/utils/use-form-state.ts

[frontend] Finished input components. 

---

apps/L1FG/instagram/frontend/specs/components/profile/Buttons.spec.tsx
apps/L1FG/instagram/frontend/specs/components/profile/IconPostSavedTag.spec.tsx
apps/L1FG/instagram/frontend/specs/components/profile/PostemptyO.spec.tsx
apps/L1FG/instagram/frontend/specs/components/profile/Profile.spec.tsx
apps/L1FG/instagram/frontend/specs/components/profile/StoryHighlight.spec.tsx
apps/L1FG/instagram/frontend/specs/components/profile/StoryHighlightModal.spec.tsx
apps/L1FG/instagram/frontend/specs/components/profile/Tagged.spec.tsx
apps/L1FG/instagram/frontend/src/components/profile/Profile.tsx
apps/L1FG/instagram/frontend/src/components/profile/isOwnerId/Buttons.tsx
apps/L1FG/instagram/frontend/src/components/profile/profilePost/PostEmpty.tsx
apps/L1FG/instagram/frontend/src/components/profile/profilePost/Tagged.tsx
apps/L1FG/instagram/frontend/src/components/profile/story/StoryHighlight.tsx
apps/L1FG/instagram/frontend/src/features/profile/comment/IconPostSavedTag.tsx

userId ownerId ylgaj haruulsan frontend 

---

apps/L1FG/instagram/frontend/specs/components/profile/Buttons.spec.tsx
apps/L1FG/instagram/frontend/specs/components/profile/Private.spec.tsx
apps/L1FG/instagram/frontend/specs/components/profile/PrivateUser.spec.tsx
apps/L1FG/instagram/frontend/specs/components/profile/Profile.spec.tsx
apps/L1FG/instagram/frontend/src/components/profile/Profile.tsx
apps/L1FG/instagram/frontend/src/components/profile/follow/Followers.tsx
apps/L1FG/instagram/frontend/src/components/profile/isOwnerId/Buttons.tsx
apps/L1FG/instagram/frontend/src/components/profile/privateUser/Private.tsx
apps/L1FG/instagram/frontend/src/components/profile/privateUser/PrivateUser.tsx
apps/L1FG/instagram/frontend/src/features/profile/PrivateProfile.tsx
apps/L1FG/instagram/frontend/src/features/profile/PublicProfile.tsx
apps/L1FG/instagram/frontend/src/features/profile/PublicProfileParent.tsx
apps/L1FG/instagram/frontend/src/features/profile/UserProfile.tsx
apps/L1FG/instagram/frontend/tsconfig.json

private frontend

---

apps/L1FG/real-state/backend/specs/resolvers/queries/post/delete-post.spec.ts
apps/L1FG/real-state/backend/src/resolvers/mutations/post/delete-post.ts
apps/L1FG/real-state/backend/src/resolvers/mutations/post/index.ts

[backend] created post delete resolver mutation

---

apps/L1FG/instagram/frontend/specs/components/profile/Buttons.spec.tsx
apps/L1FG/instagram/frontend/specs/components/profile/Followers.spec.tsx
apps/L1FG/instagram/frontend/specs/components/profile/Following.spec.tsx
apps/L1FG/instagram/frontend/src/components/profile/follow/Followers.tsx
apps/L1FG/instagram/frontend/src/components/profile/follow/Following.tsx
apps/L1FG/instagram/frontend/src/components/profile/isOwnerId/Buttons.tsx
apps/L1FG/instagram/frontend/src/components/svg/TaggedIcon.tsx
apps/L1FG/instagram/frontend/src/features/notification/RequestFollow.tsx
apps/L1FG/instagram/frontend/src/features/profile/comment/CreateComment.tsx
apps/L1FG/instagram/frontend/src/features/profile/comment/GetComments.tsx
apps/L1FG/instagram/frontend/src/features/profile/comment/IconPostSavedTag.tsx
apps/L1FG/instagram/frontend/src/graphql/comment.graphql
apps/L1FG/instagram/frontend/src/graphql/follow.graphql
apps/L1FG/instagram/frontend/src/graphql/notification.graphql

profile following followers frontend data duudaj avchirsan

---

apps/L1FG/instagram/frontend/src/components/profile/follow/Followers.tsx
apps/L1FG/instagram/frontend/src/components/providers/CacheProvider.tsx
apps/L1FG/instagram/frontend/src/features/home-post/FriendshipStatusUser.tsx
apps/L1FG/instagram/frontend/src/features/home-post/Remove.tsx
apps/L1FG/instagram/frontend/src/graphql/follow.graphql

remove follow frontend data duudaj avchriv

---

apps/L1FG/instagram/backend/specs/resolvers/queries/story/get-one-story.spec.ts
apps/L1FG/instagram/backend/src/resolvers/queries/story/get-one-story.ts
apps/L1FG/instagram/backend/src/resolvers/queries/story/get-user-story-info.ts
apps/L1FG/instagram/backend/src/schemas/story.schema.ts

getOneStory 

---

apps/L1FG/restaurant/frontend/cypress/utils/all-pages.json
apps/L1FG/restaurant/frontend/specs/components/admin/ad-login.spec.tsx
apps/L1FG/restaurant/frontend/specs/components/admin/admin-header.spec.tsx
apps/L1FG/restaurant/frontend/src/app/admin/layout.tsx
apps/L1FG/restaurant/frontend/src/app/admin/login/page.tsx
apps/L1FG/restaurant/frontend/src/components/admin-page-comp/AdminHeader.tsx
apps/L1FG/restaurant/frontend/src/components/admin-page-comp/AdminLogin.tsx

feat(frontend): frontend

---

apps/L1US/chatbot/backend/specs/resolvers/queries/user/get-user.spec.ts
apps/L1US/chatbot/backend/src/resolvers/queries/index.ts
apps/L1US/chatbot/backend/src/resolvers/queries/user/get-user.ts
apps/L1US/chatbot/backend/src/resolvers/queries/user/index.ts
apps/L1US/chatbot/backend/src/schemas/user.schema.ts

****Description****
This PR adds the implementation and unit tests for the getUser GraphQL resolver. The resolver retrieves user details based on the provided id, ensuring proper error handling for invalid or missing users.
**Changes Made**
Implemented getUser resolver in resolvers/queries.ts
Added validation to check if the provided id is a valid MongoDB ObjectId
Ensured proper error handling for invalid IDs, non-existent users, and database failures
Created get-user.spec.ts to test various scenarios, including:
Valid user retrieval
Handling of invalid user IDs
Case where the user is not found
Database failure handling
**How to Test**
Run unit tests with jest to verify functionality:
yarn nx test get-user.spec.ts
Ensure all tests pass and cover edge cases.
**Additional Notes**
Mocked …

Implement getUser Resolver and Unit Tests

---

apps/L2A/README.md

feat(real estate): test

---

apps/L2A/restaurant/frontend/cypress/e2e/homeBody.cy.tsx
apps/L2A/restaurant/frontend/project.json
apps/L2A/restaurant/frontend/spec/sheet.spec.tsx
apps/L2A/restaurant/frontend/src/app/_components/Sheet.tsx
apps/L2A/restaurant/frontend/src/app/_features/HomeBody.tsx
apps/L2A/restaurant/frontend/src/app/page.tsx

feat: new sheet

---

.gitignore
apps/L2A/restaurant/backend/specs/resolvers/mutations/add-product.spec.ts
apps/L2A/restaurant/backend/specs/resolvers/mutations/update-product.spec.ts
apps/L2A/restaurant/backend/src/app/page.tsx
apps/L2A/restaurant/backend/src/models/category.model.ts
apps/L2A/restaurant/backend/src/models/product.model.ts
apps/L2A/restaurant/backend/src/resolvers/index.ts
apps/L2A/restaurant/backend/src/resolvers/mutations/add-product.ts
apps/L2A/restaurant/backend/src/resolvers/mutations/index.ts
apps/L2A/restaurant/backend/src/resolvers/mutations/update-product.ts
apps/L2A/restaurant/backend/src/schemas/category.schema.ts
apps/L2A/restaurant/backend/src/schemas/index.ts
apps/L2A/restaurant/backend/src/schemas/product.schema.ts
apps/L2A/restaurant/backend/src/services/product.service.ts
apps/L2A/restaurant/backend/src/utils/build-update-data.ts
apps/L2A/restaurant/backend/src/utils/connect-to-db.ts
apps/L2A/restaurant/backend/src/utils/validate-product-input.ts
apps/L2A/restaurant/backend/src/utils/validate-update-input.ts

feat: backend for product

---

apps/L2A/concert/backend/specs/resolvers/queries/get-concert.spec.ts
apps/L2A/concert/backend/src/resolvers/queries/get-concert.ts
apps/L2A/concert/backend/src/resolvers/queries/index.ts
apps/L2A/concert/backend/src/schemas/queries.shema.ts
apps/L2A/concert/frontend/src/app/event/[id]/_components/AboutEvent.tsx
apps/L2A/concert/frontend/src/graphql/all.graphql

get concert query

---

apps/L2A/restaurant/frontend/cypress/e2e/admin/admin-table-semiheader.cy.tsx
apps/L2A/restaurant/frontend/project.json
apps/L2A/restaurant/frontend/specs/admin/tableSemiHeader.spec.tsx
apps/L2A/restaurant/frontend/src/app/admin/table/_features/AdminTableSemiHeader.tsx
apps/L2A/restaurant/frontend/src/app/admin/table/page.tsx

table add dialog

---

apps/L2A/concert/frontend/project.json
apps/L2A/concert/frontend/src/app/admin/login/page.tsx

fix: changed vercel front end project id
concert bagiin ahlagch ni uuriihuu project iin file iig uurchilsn

fix: changed vercel front end project id

---

apps/L2B/tinder/tinder-frontend/cypress/e2e/auth/sign-up/index.cy.tsx
apps/L2B/tinder/tinder-frontend/specs/sign-up/SecondStep.spec.tsx
apps/L2B/tinder/tinder-frontend/src/app/auth/sign-up/_components/SecondStep.tsx
apps/L2B/tinder/tinder-frontend/src/app/auth/sign-up/_feature/SignUpSteps.tsx

feat: sign up second step frontend done (otp code iin daraa ni hiine!!!)

feat: sign up second step frontend done

---

apps/L2B/tinder/tinder-frontend/specs/forget-password/PasswordSchema.spec.tsx
apps/L2B/tinder/tinder-frontend/specs/forget-password/ThirdStep.spec.tsx
apps/L2B/tinder/tinder-frontend/src/app/auth/forget-password/_components/PasswordSchema.tsx
apps/L2B/tinder/tinder-frontend/src/app/auth/forget-password/_components/ThirdStep.tsx

created forget-password third page front-end

feat: created forget-password third page front-end

---

apps/L2B/tinder/tinder-frontend/cypress/e2e/auth/sign-in/index.cy.tsx
apps/L2B/tinder/tinder-frontend/src/app/auth/sign-in/page.tsx

feat: signin done

---

apps/L2B/tinder/tinder-backend/project.json

feat: backend project id buruu baigaad zasaw

feat: backend project id buruu baigaad zasaw

---

apps/L2B/tinder/tinder-frontend/src/graphql/all.graphql

graphql frontend nemew tehku bol bagiihan frontend ee asaaj chadahgui baisan bolhoor issue nese gajuud yum hiiw

feat: graphql frontend nemew

---

apps/L2B/tinder/tinder-frontend/cypress/e2e/auth/sign-up/index.cy.tsx
apps/L2B/tinder/tinder-frontend/specs/sign-up/ThirdStep.spec.tsx
apps/L2B/tinder/tinder-frontend/src/app/auth/sign-up/_components/ThirdStep.tsx

deleted previous branch and started from scratch

feat(component): created new component

---

Ellipse 1.svg
apps/L2B/hotel-booking/client/specs/Header.spec.tsx
apps/L2B/hotel-booking/client/src/app/_components/Card/Page.tsx
apps/L2B/hotel-booking/client/src/app/_components/Header.tsx
apps/L2B/hotel-booking/client/src/app/layout.tsx

feat: header test

---

.github/workflows/ci.yml

Reverts pinecone-studio/pinecone-intern-monorepo#5176

Revert "feat: change install commands"

---

apps/L2B/tinder/tinder-frontend/cypress/e2e/auth/sign-in/index.cy.tsx
apps/L2B/tinder/tinder-frontend/src/app/auth/sign-in/page.tsx
apps/L2B/tinder/tinder-frontend/src/app/layout.tsx
apps/L2B/tinder/tinder-frontend/src/graphql/user.graphql

fix: sign-in front back holboson

---

apps/L2B/tinder/tinder-backend/specs/resolvers/queries/fetch-profile.spec.ts
apps/L2B/tinder/tinder-backend/src/models/profile.model.ts
apps/L2B/tinder/tinder-backend/src/resolvers/queries/fetch-profile.ts
apps/L2B/tinder/tinder-backend/src/resolvers/queries/index.ts
apps/L2B/tinder/tinder-backend/src/schemas/profile.schema.ts

add fetch profile

---

apps/L2B/tinder/tinder-backend/next.config.js

feat: fixed

---

apps/L2B/tinder/tinder-backend/specs/resolvers/mutations/profile/update-profile.spec.ts
apps/L2B/tinder/tinder-backend/src/resolvers/mutations/index.ts
apps/L2B/tinder/tinder-backend/src/resolvers/mutations/profile/update-image.ts
apps/L2B/tinder/tinder-backend/src/schemas/profile.schema.ts

feat: edit profile backend

---

apps/L2B/tinder/tinder-backend/specs/resolvers/mutations/profile/update-profile-image.spec.ts
apps/L2B/tinder/tinder-backend/src/resolvers/mutations/profile/update-image.ts
apps/L2B/tinder/tinder-backend/src/schemas/profile.schema.ts

5288 profile image update array orj irdg bolgo

---

apps/L2B/tinder/tinder-backend/specs/resolvers/mutations/match/dislike.spec.ts
apps/L2B/tinder/tinder-backend/specs/resolvers/mutations/match/like.spec.ts
apps/L2B/tinder/tinder-backend/src/models/profile.model.ts
apps/L2B/tinder/tinder-backend/src/resolvers/mutations/index.ts
apps/L2B/tinder/tinder-backend/src/resolvers/mutations/match/dislike.ts
apps/L2B/tinder/tinder-backend/src/resolvers/mutations/match/match.ts
apps/L2B/tinder/tinder-backend/src/schemas/profile.schema.ts

feat: match

---

apps/L2B/tinder/tinder-backend/specs/resolvers/mutations/match/dislike.spec.ts
apps/L2B/tinder/tinder-backend/src/resolvers/mutations/match/dislike.ts

fix: change font

---

apps/L1G/tinder/tinder-frontend/graphql/getusers.graphql
apps/L1G/tinder/tinder-frontend/src/graphql/hello-query.graphql
apps/L1G/tinder/tinder-frontend/src/graphql/mutations/like.graphql
apps/L1G/tinder/tinder-frontend/src/graphql/mutations/login.graphql
apps/L1G/tinder/tinder-frontend/src/graphql/mutations/signup.graphql
apps/L1G/tinder/tinder-frontend/src/graphql/queries/getusers.graphql

[FE] codegen setup graphql shemanuudaa bichiv

codegen setup

---

apps/L1G/tinder/tinder-frontend/src/app/(main)/profile/page.tsx
apps/L1G/tinder/tinder-frontend/src/components/ProfileImages.tsx

[FE] Imageupload component design

[FE] Imageupload component design

---

apps/L1G/tinder/tinder-backend/src/handler.ts
apps/L1G/tinder/tinder-backend/src/resolvers/mutations/image-upload.ts
apps/L1G/tinder/tinder-frontend/cypress/utils/all-pages.json
apps/L1G/tinder/tinder-frontend/specs/ProfileImages.spec.tsx
apps/L1G/tinder/tinder-frontend/src/app/providers/Appollo.tsx
apps/L1G/tinder/tinder-frontend/src/components/ProfileImages.tsx
apps/L1G/tinder/tinder-frontend/src/graphql/mutations/image-upload.graphql

feat: image upload Frontoos Back ruu ilgeedeg bolson

---

apps/L1G/tinder/tinder-frontend/specs/ResetPassword.spec.tsx
apps/L1G/tinder/tinder-frontend/src/components/ResetPassword.tsx

fix: router fix

---

apps/L1G/tinder/tinder-backend/specs/resolvers/queries/get-user-by-id.spec.ts
apps/L1G/tinder/tinder-backend/src/resolvers/index.ts
apps/L1G/tinder/tinder-backend/src/resolvers/queries/get-user-by-id.ts
apps/L1G/tinder/tinder-backend/src/resolvers/queries/index.ts
apps/L1G/tinder/tinder-backend/src/schemas/user.ts

feat(get user by id): get user by id

---

apps/L1G/tinder/tinder-backend/specs/resolvers/queries/me.spec.ts
apps/L1G/tinder/tinder-backend/src/resolvers/index.ts
apps/L1G/tinder/tinder-backend/src/resolvers/queries/me.ts
apps/L1G/tinder/tinder-backend/src/types/index.ts
apps/L1G/tinder/tinder-frontend/src/app/(main)/home/page.tsx
apps/L1G/tinder/tinder-frontend/src/app/contexts/CurrentUserContext.tsx
apps/L1G/tinder/tinder-frontend/src/app/layout.tsx
apps/L1G/tinder/tinder-frontend/src/graphql/queries/me.graphql

5861 current userid front deer avdag bolgoh

---

apps/L1G/restaurant/restaurant-backend/specs/resolvers/mutation/discount/create-discount.spec.ts
apps/L1G/restaurant/restaurant-backend/specs/resolvers/mutation/discount/delete-discount.spec.ts
apps/L1G/restaurant/restaurant-backend/specs/resolvers/mutation/discount/update-discount.spec.ts
apps/L1G/restaurant/restaurant-backend/specs/resolvers/queries/discount/get-discounts.spec.ts
apps/L1G/restaurant/restaurant-backend/src/models/discount.model.ts
apps/L1G/restaurant/restaurant-backend/src/resolvers/mutations/discount/create-discount.ts
apps/L1G/restaurant/restaurant-backend/src/resolvers/mutations/discount/delete-discount.ts
apps/L1G/restaurant/restaurant-backend/src/resolvers/mutations/discount/update-discount.ts
apps/L1G/restaurant/restaurant-backend/src/resolvers/mutations/index.ts
apps/L1G/restaurant/restaurant-backend/src/resolvers/queries/discount/get-discounts.ts
apps/L1G/restaurant/restaurant-backend/src/resolvers/queries/index.ts
apps/L1G/restaurant/restaurant-backend/src/schemas/discount.schema.ts
apps/L1G/restaurant/restaurant-backend/src/schemas/index.ts
apps/L1G/restaurant/restaurant-backend/src/utils/types/discount-type.ts

discount backend 
- create, update, delete

feat(restaurant-backend-discount): create, update, delete discount

---

apps/L1G/tinder/socket-server/package.json
apps/L1G/tinder/socket-server/src/server.ts
apps/L1G/tinder/socket-server/tsconfig.json
apps/L1G/tinder/tinder-backend/src/server.ts

fix: socket server setup hiiv

---

apps/L1G/tinder/tinder-backend/specs/resolvers/queries/get-user-by-id.spec.ts
apps/L1G/tinder/tinder-backend/specs/resolvers/queries/getusers.spec.ts
apps/L1G/tinder/tinder-backend/src/resolvers/queries/get-user-by-id.ts
apps/L1G/tinder/tinder-backend/src/resolvers/queries/getusers.ts

5896 be getuser interestname fix

---

apps/L1G/restaurant/restaurant-backend/specs/resolvers/mutation/food/update-food-by-status.spec.ts
apps/L1G/restaurant/restaurant-backend/src/resolvers/mutations/food/update-food-by-status.ts
apps/L1G/restaurant/restaurant-backend/src/schemas/food.schema.ts
apps/L1G/restaurant/restaurant-frontend/specs/(admin)/components/food/FoodCreateDialog.spec.tsx
apps/L1G/restaurant/restaurant-frontend/specs/(admin)/components/food/FoodUpdateDialog.spec.tsx
apps/L1G/restaurant/restaurant-frontend/specs/(admin)/components/food/FoodUpdateForm.spec.tsx
apps/L1G/restaurant/restaurant-frontend/specs/utils/FoodMockData.tsx
apps/L1G/restaurant/restaurant-frontend/src/common/graphql/discount.graphql
apps/L1G/restaurant/restaurant-frontend/src/common/graphql/food.graphql
apps/L1G/restaurant/restaurant-frontend/src/components/admin/food/AllFoodsCard.tsx
apps/L1G/restaurant/restaurant-frontend/src/components/admin/food/FoodCreateDialog.tsx
apps/L1G/restaurant/restaurant-frontend/src/components/admin/food/FoodUpdateDialog.tsx
apps/L1G/restaurant/restaurant-frontend/src/components/admin/food/FoodUpdateForm.tsx
apps/L1G/restaurant/restaurant-frontend/src/utils/FoodTypes.tsx

changed food graphql
added discount graphql

fix(restaurant-frontend food): change food graphql, add discount graphql

---

apps/L1G/restaurant/restaurant-backend/src/resolvers/mutations/index.ts
apps/L1G/restaurant/restaurant-frontend/specs/(admin)/components/menu/CategoryCreateDialog.spec.tsx
apps/L1G/restaurant/restaurant-frontend/specs/(admin)/components/menu/DiscountCreateDialog.spec.tsx
apps/L1G/restaurant/restaurant-frontend/specs/utils/FoodMockData.tsx
apps/L1G/restaurant/restaurant-frontend/src/components/admin/food/FoodCreateDialog.tsx
apps/L1G/restaurant/restaurant-frontend/src/components/admin/menu/CategoryCreateDialog.tsx
apps/L1G/restaurant/restaurant-frontend/src/components/admin/menu/DiscountCreateDialog.tsx
apps/L1G/restaurant/restaurant-frontend/src/components/admin/menu/FormFieldInput.tsx
apps/L1G/restaurant/restaurant-frontend/src/helpers/form-schemas.ts

admin - menu
- create new category and discount (component)

feat(restaurant-frontend admin-menu): create new category and discount

---

apps/L1G/tinder/socket-server/src/server.ts

feat: server update

---

apps/L1G/tinder/socket-server/src/server.ts

fix: butsaalaa

---

apps/L1G/tinder/socket-server/src/server.ts

feat: seen logic

---

apps/L1G/tinder/tinder-backend/src/resolvers/queries/getusers.ts
apps/L1G/tinder/tinder-frontend/specs/FormField.spec.tsx
apps/L1G/tinder/tinder-frontend/specs/Interest.spec.tsx
apps/L1G/tinder/tinder-frontend/specs/Loading.spec.tsx
apps/L1G/tinder/tinder-frontend/specs/MyProfileForm.spec.tsx
apps/L1G/tinder/tinder-frontend/specs/TinderCard-Profile.spec.tsx
apps/L1G/tinder/tinder-frontend/specs/TinderCard-image.spec.tsx
apps/L1G/tinder/tinder-frontend/specs/TinderCardParts.spec.tsx
apps/L1G/tinder/tinder-frontend/src/app/(main)/home/page.tsx
apps/L1G/tinder/tinder-frontend/src/app/page.tsx
apps/L1G/tinder/tinder-frontend/src/components/FormNew.tsx
apps/L1G/tinder/tinder-frontend/src/components/Interest.tsx
apps/L1G/tinder/tinder-frontend/src/components/Loading.tsx
apps/L1G/tinder/tinder-frontend/src/components/TinderCardParts.tsx
apps/L1G/tinder/tinder-frontend/src/graphql/queries/getusers.graphql

user card dr zuragnii toonoos hamaarch interest haragdana

feat(tinder card): user interest in home page

---

apps/L1G/restaurant/restaurant-backend/specs/resolvers/mutation/table/delete-table.spec.ts
apps/L1G/restaurant/restaurant-backend/specs/resolvers/queries/order/get-order-by-userId.spec.ts
apps/L1G/restaurant/restaurant-backend/src/resolvers/mutations/auth/sign-in.ts

jwt sign with user instead od user._id

jwt sign with user instead od user._id

---

apps/L1G/tinder/socket-server/src/server.ts

fix: server fix

---

apps/L1G/tinder/tinder-backend/specs/resolvers/mutations/unmatch.spec.ts
apps/L1G/tinder/tinder-backend/src/resolvers/mutations/unmatch.ts
apps/L1G/tinder/tinder-frontend/hooks/useSocketConnection.ts
apps/L1G/tinder/tinder-frontend/hooks/useUserManagement.ts
apps/L1G/tinder/tinder-frontend/specs/ChatHeader.spec.tsx
apps/L1G/tinder/tinder-frontend/specs/ChatPage.spec.tsx
apps/L1G/tinder/tinder-frontend/specs/HowOldAreYou.spec.tsx
apps/L1G/tinder/tinder-frontend/specs/UnmatchButton.spec.tsx
apps/L1G/tinder/tinder-frontend/src/components/ChatHeader.tsx
apps/L1G/tinder/tinder-frontend/src/components/ChatPage.tsx
apps/L1G/tinder/tinder-frontend/src/components/ChatWindow.tsx
apps/L1G/tinder/tinder-frontend/src/components/UnmatchButton.tsx
apps/L1G/tinder/tinder-frontend/src/graphql/mutations/unmatch.graphql

5965 be to fe unmatch logic

---

apps/L1G/tinder/tinder-frontend/specs/ItsAmAtch.spec.tsx
apps/L1G/tinder/tinder-frontend/src/app/(main)/home/page.tsx
apps/L1G/tinder/tinder-frontend/src/components/ItsAmAtch.tsx

feat(match animation done): done

---

apps/L1G/tinder/tinder-frontend/specs/BirthDateField.spec.tsx
apps/L1G/tinder/tinder-frontend/specs/MyImages.spec.tsx
apps/L1G/tinder/tinder-frontend/specs/MyProfile.spec.tsx
apps/L1G/tinder/tinder-frontend/specs/MyProfileForm.spec.tsx
apps/L1G/tinder/tinder-frontend/specs/ProfessionSchoolFields.spec.tsx
apps/L1G/tinder/tinder-frontend/src/components/BirthDateField.tsx
apps/L1G/tinder/tinder-frontend/src/components/MyImages.tsx
apps/L1G/tinder/tinder-frontend/src/components/MyProfile.tsx
apps/L1G/tinder/tinder-frontend/src/components/MyProfileForm.tsx
apps/L1G/tinder/tinder-frontend/utils/date-utils.ts

6003 update only test

---

apps/L1G/tinder/socket-server/src/server.ts

fix: serveer

---

apps/L1G/restaurant/restaurant-backend/src/models/order.model.ts
apps/L1G/restaurant/restaurant-backend/src/models/user.model.ts
apps/L1G/restaurant/restaurant-backend/src/resolvers/mutations/order/create-order.ts
apps/L1G/restaurant/restaurant-backend/src/schemas/order.schema.ts

backend bug fix order and user

feat((restaurant-backend)): backend bug fix order and user

---

apps/L1G/tinder/socket-server/src/server.ts

fix: update

---

apps/L1G/tinder/tinder-frontend/specs/MultiSelect.spec.tsx
apps/L1G/tinder/tinder-frontend/specs/OptionList.spec.tsx
apps/L1G/tinder/tinder-frontend/src/components/MultiSelect.tsx
apps/L1G/tinder/tinder-frontend/src/components/OptionList.tsx

fix(select all btn): deleted select all btn in interests

---

apps/L1G/tinder/tinder-backend/specs/resolvers/mutations/auth/delete-user.spec.ts
apps/L1G/tinder/tinder-backend/src/resolvers/index.ts
apps/L1G/tinder/tinder-backend/src/resolvers/mutations/auth/delete-user.ts
apps/L1G/tinder/tinder-backend/src/resolvers/mutations/auth/index.ts
apps/L1G/tinder/tinder-backend/src/schemas/user.ts
apps/L1G/tinder/tinder-backend/src/types/index.ts

feat([be] delete-user id): be

---

apps/L1G/restaurant/restaurant-frontend/specs/(admin)/order/OrderContainer.spec.tsx
apps/L1G/restaurant/restaurant-frontend/specs/(admin)/order/OrderStatusUpdate.spec.tsx
apps/L1G/restaurant/restaurant-frontend/specs/(admin)/order/OrderedFoods.spec.tsx
apps/L1G/restaurant/restaurant-frontend/src/app/(admin)/layout.tsx
apps/L1G/restaurant/restaurant-frontend/src/app/(admin)/order/page.tsx
apps/L1G/restaurant/restaurant-frontend/src/app/layout.tsx
apps/L1G/restaurant/restaurant-frontend/src/common/graphql/order.graphql
apps/L1G/restaurant/restaurant-frontend/src/components/admin/order/OrderContainer.tsx
apps/L1G/restaurant/restaurant-frontend/src/components/admin/order/OrderItem.tsx
apps/L1G/restaurant/restaurant-frontend/src/components/admin/order/OrderedFoods.tsx
apps/L1G/restaurant/restaurant-frontend/src/components/admin/order/UpdateFoodOrderStatus.tsx

feat(restaurant-frontend): update order status

feat(restaurant-frontend): update order status

---

apps/L1G/tinder/tinder-frontend/specs/TinderCard-Profile.spec.tsx
apps/L1G/tinder/tinder-frontend/specs/TinderCardContent.spec.tsx
apps/L1G/tinder/tinder-frontend/specs/TinderCardLayout.spec.tsx
apps/L1G/tinder/tinder-frontend/specs/TinderCardParts.spec.tsx
apps/L1G/tinder/tinder-frontend/src/app/(main)/home/page.tsx
apps/L1G/tinder/tinder-frontend/src/components/Header.tsx
apps/L1G/tinder/tinder-frontend/src/components/ProfileSwiper.tsx
apps/L1G/tinder/tinder-frontend/src/components/TinderCard.tsx
apps/L1G/tinder/tinder-frontend/src/components/TinderCardContent.tsx
apps/L1G/tinder/tinder-frontend/src/components/TinderCardLayout.tsx
apps/L1G/tinder/tinder-frontend/src/components/TinderCardParts.tsx
apps/L1G/tinder/tinder-frontend/tailwind.config.js
apps/L1G/tinder/tinder-frontend/utils/tinder-card-handlers.ts

6093 swipe animation saijruulah gej uzne

---

apps/L1G/tinder/tinder-backend/src/resolvers/queries/get-other-users.ts

fix: bug fixed

---

apps/L1G/tinder/tinder-frontend/specs/MyProfile.spec.tsx
apps/L1G/tinder/tinder-frontend/src/app/providers/Appollo.tsx
apps/L1G/tinder/tinder-frontend/src/components/MyProfile.tsx
apps/L1G/tinder/tinder-frontend/utils/apollo-client.ts

fix: apollo clear cache

---

apps/L1G/tinder/socket-server/src/server.ts

fix: fixed

---

apps/L1G/tinder/tinder-backend/specs/resolvers/mutations/like.spec.ts
apps/L1G/tinder/tinder-backend/src/resolvers/mutations/like.ts
apps/L1G/tinder/tinder-backend/src/schemas/user.ts
apps/L1G/tinder/tinder-frontend/hooks/usePendingMessages.ts
apps/L1G/tinder/tinder-frontend/specs/ItsAmAtch.spec.tsx
apps/L1G/tinder/tinder-frontend/specs/ProfileSwiper.spec.tsx
apps/L1G/tinder/tinder-frontend/src/app/(main)/home/page.tsx
apps/L1G/tinder/tinder-frontend/src/app/contexts/CurrentUserContext.tsx
apps/L1G/tinder/tinder-frontend/src/app/page.tsx
apps/L1G/tinder/tinder-frontend/src/components/ChatPage.tsx
apps/L1G/tinder/tinder-frontend/src/components/ItsAmAtch.tsx
apps/L1G/tinder/tinder-frontend/src/components/MatchDialogClose.tsx
apps/L1G/tinder/tinder-frontend/src/components/ProfileSwiper.tsx
apps/L1G/tinder/tinder-frontend/src/graphql/mutations/like.graphql
apps/L1G/tinder/tinder-frontend/utils/global-message-bridge.ts
apps/L1G/tinder/tinder-frontend/utils/match-popup.ts
apps/L1G/tinder/tinder-frontend/utils/popup.ts
apps/L1G/tinder/tinder-frontend/utils/user.ts

6105 fix matched dailog

---

apps/L1G/restaurant/restaurant-frontend/specs/(public)/components/navbar/OrderHistory.spec.tsx
apps/L1G/restaurant/restaurant-frontend/specs/components/payment/PaymentLogic.spec.tsx
apps/L1G/restaurant/restaurant-frontend/specs/components/payment/PaymentSelection.spec.tsx
apps/L1G/restaurant/restaurant-frontend/src/app/(admin)/layout.tsx
apps/L1G/restaurant/restaurant-frontend/src/app/(private)/update-user/page.tsx
apps/L1G/restaurant/restaurant-frontend/src/common/graphql/food.graphql
apps/L1G/restaurant/restaurant-frontend/src/components/Navbar.tsx
apps/L1G/restaurant/restaurant-frontend/src/components/OrderHistory.tsx
apps/L1G/restaurant/restaurant-frontend/src/components/WalletComponent.tsx
apps/L1G/restaurant/restaurant-frontend/src/components/admin/menu/MenuProductCard.tsx
apps/L1G/restaurant/restaurant-frontend/src/components/payment/PaymentSelection.tsx
apps/L1G/restaurant/restaurant-frontend/src/utils/PaymentLogic.tsx

restaurant-frontend bug fix

---

apps/L1G/restaurant/restaurant-frontend/src/app/(public)/orderDetail/page.tsx
apps/L1G/restaurant/restaurant-frontend/src/components/home/HomePageContainer.tsx

restaurant-frontend-order-by-user

restaurant-frontend-order-by-user

---

apps/L1G/tinder/socket-server/src/server.ts

fix: url add
